GET http://localhost:3101/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTMyNzM1MzYsImV4cCI6MTc1MzI3MzU2Nn0.LMWH6yOISm6CmfGoh_f14i4dSMc64QLAe9ci8ZEnsvc

###
POST http://localhost:3102/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTMyNzM1MDN9.BS0UkfyQrUHtbkyv5wy4kNCtGaRavoqKNpdXuwGtLag"
}

###
POST http://localhost:3102/login
Content-Type: application/json

{
  "username": "test1"
}
